[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
process_path = "0.1.4"
rust-crypto="0.2.36"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }